# Site settings
title: PRTY CHAT
email: andre@prtychat.com
url: http://prtychat.com/
description: "Snap a flash status, squad up, live the moment together"
youtubeId: YrRKrj3-kLU
#baseurl: '/worldview'

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#9013FE'
  primary-light: '#DC59EF'
  links: '#9013FE'
  button: '#AF0BAA'

# Footer settings
footer: PRTY CHAT

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/getflashsquad
  - title: facebook
    url: https://www.facebook.com/Flash-Squad-1568768496781115/

# Router
home: "/"
about: "/#about/"
download: "/#download/"
contact: "/#contact/"
privacy: "/privacy/"

# Build settings
markdown: kramdown
permalink: pretty
